name: arduino-esp8266-build.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Compila o codigo
        uses: ./github-actions-with-docker/arduino-esp8266-build # Uses an action in the action directory
        id: hello
        with:
          repository-github: guilhermerodrigues680/Interligando-NodeMCU-e-GoPro
          path-ino-file: NodeMCUeGoPro
          ino-file: NodeMCUeGoPro.ino
      
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"