name: Teste CI

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  # Testes
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: debug-annotation
      run: echo "::debug::Esta é uma anotação de debug (É necessario ACTIONS_STEP_DEBUG=true)"

    - name: warning-annotation
      run: echo "::warning::Esta é uma anotação de warning"

    - name: error-annotation
      run: echo "::error::Esta é uma anotação de error"

    - name: debug-file-annotation
      run: echo "::debug file=.github/workflows/msgteste.yml,line=28,col=7::Linkando debug (É necessario ACTIONS_STEP_DEBUG=true)"

    - name: warning-file-annotation
      run: echo "::warning file=.github/workflows/msgteste.yml,line=31,col=7::Linkando warning"

    - name: error-file-annotation
      run: echo "::error file=.github/workflows/msgteste.yml,line=34,col=7::Linkando error"

    # - name: Build the Docker image
    #   run: docker build . --file testes.Dockerfile --tag testes:latest

    # - name: Print Docker image size
    #   run: docker images | grep testes