# Orientações:
# Altere a variavel de ambiente PATH_INO_FILE para o caminho do programa

name: Compilação

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published, created, edited]

jobs:
  build:
    name: Compilando NodeMCUeGoPro.ino
    runs-on: ubuntu-18.04
    env: 
      PATH_INO_FILE: Interligando-NodeMCU-e-GoPro/NodeMCUeGoPro/NodeMCUeGoPro.ino
    steps:
      
      # Download e instação da Arduino IDE para ultilizar as Arduino CLI
      - name: Baixar e instalar Arduino IDE 1.8.12 64bits
        run: |
          wget -q https://downloads.arduino.cc/arduino-1.8.12-linux64.tar.xz
          sudo mv arduino-1.8.12-linux64.tar.xz /opt
          cd /opt
          sudo tar -xf arduino-1.8.12-linux64.tar.xz
          cd arduino-1.8.12
          sudo ./install.sh >/dev/null
          # which arduino
          # ls -la $(which arduino) | grep 'arduino'

      # Instalação das placas ESP8266 no Arduino IDE
      - name: Instalar Placa ESP8266 no Arduino
        run: |
          mkdir -p /home/runner/Arduino/hardware/esp8266com
          cd /home/runner/Arduino/hardware/esp8266com
          git clone https://github.com/esp8266/Arduino.git esp8266 --quiet
          cd esp8266
          git checkout 2.6.3 --quiet
          git submodule update --init --quiet
          cd tools
          python3 get.py > /dev/null

      # Checkout para $GITHUB_WORKSPACE para o Actions acessar o repositorio
      - uses: actions/checkout@v2

      # - name: Update Submodules
      #   run: |
      #     sudo apt -qq update >/dev/null && sudo apt -qq install tree -y >/dev/null
      #     # git submodule update --init > /dev/null
      #     pwd
      #     tree

      # Compilando o codigo para o NodeMCU
      - name: Compliando o programa
        run: python3 generate-anotations.py




# Referencias:
# https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
# https://arduino-esp8266.readthedocs.io/en/latest/installing.html
# https://gist.github.com/bergie/0dcdf0730765602ccfb4cf3a61b92989
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults