name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Arduino ESP8266
      run: docker build . --file arduino-esp8266.Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Build the Docker image PlatformIO
      run: docker build . --file platformio.Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Build the Docker image Testes
      run: docker build . --file testes.Dockerfile --tag my-image-name:$(date +%s)

    - name: Check images size
      run: docker images