name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Copila todos os Dockerfiles e checa o tamanho da imagem
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Somente nome, ex: <nome>.Dockerfile
        dockerfile: [arduino-esp8266, platformio, testes ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.dockerfile }}.Dockerfile --tag ${{ matrix.dockerfile }}:latest

    - name: Print Docker image size
      run: docker images | grep "${{ matrix.dockerfile }}"

    - uses: actions/checkout@v1
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        # path: path/to/artifact
        path: path