name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Copila todos os Dockerfiles e checa o tamanho da imagem
  dockerfiles:
    name: Dockerfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Somente nome, ex: <nome>.Dockerfile
        dockerfile: [arduino-esp8266, platformio, testes ]

    steps:
    - uses: actions/checkout@v2
    - name: Build de todas imagens Docker
      run: docker build . --file ${{ matrix.dockerfile }}.Dockerfile --tag ${{ matrix.dockerfile }}:latest

    - name: Check image size
      run: docker images | grep "${{ matrix.dockerfile }}"