name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Copila todos os Dockerfiles e checa o tamanho da imagem
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Somente nome, ex: <nome>.Dockerfile
        dockerfile: [arduino-esp8266, platformio, testes ]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.dockerfile }}.Dockerfile --tag ${{ matrix.dockerfile }}:latest

    - name: Print Docker image size
      run: docker images | grep "${{ matrix.dockerfile }}"

    # - name: Salvar log do tamanho da imagem
    - run: mkdir -p artifacts/logs
    - run: echo $(docker images | grep "${{ matrix.dockerfile }}") >> artifacts/logs/image-size.txt
    - uses: actions/upload-artifact@v1
      with:
        name: logs
        path: artifacts

  print-artifacts:
    name: Imprime Logs
    # needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwd && ls
    # - name: ler log
    - uses: actions/download-artifact@v1
      with:
        name: logs
        path: artifacts
    # - name: ler log
    - run: ls
    # - run: cat logs/logs/image-size.txt