name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Copila todos os Dockerfiles e checa o tamanho da imagem
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Somente nome, ex: <nome>.Dockerfile
        # dockerfile: [arduino-esp8266, platformio, testes ]
        # dockerfile: [ platformio, testes ]
        dockerfile: [ testes ]

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file ${{ matrix.dockerfile }}.Dockerfile --tag ${{ matrix.dockerfile }}:latest

    - name: Print Docker image size
      run: docker images | grep "${{ matrix.dockerfile }}"

    - name: Salvar no log o tamanho da imagem
      run: |
        mkdir -p artifacts/logs
        echo $(docker images | grep "${{ matrix.dockerfile }}") >> artifacts/logs/image-size-${{ matrix.dockerfile }}.txt

    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: artifacts

  print-artifacts:
    name: Imprimir Logs
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Instalar o tree
      run: sudo apt install tree -y

    - name: Baixar logs
      uses: actions/download-artifact@v1
      with:
        name: logs
        path: artifacts
    
    - name: Ler log
      run: |
        pwd
        tree
        cd artifacts/logs/
        ls | xargs -n 1 sh -c 'echo "\n\n------- $0\n"; cat $0'

    # Modelo de print-artifacts
    # print-artifacts:
    # name: Imprime Logs
    # runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v2
    # - run: pwd && ls
    # - uses: actions/download-artifact@v1
    #   with:
    #     name: logs
    #     path: artifacts
    # - run: ls