name: Teste CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Testes
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "::debug ::Entered octocatAddition method"
    - run: echo "::warn ::Entered octocatAddition method"
    - run: echo "::error ::Entered octocatAddition method"

    # - name: Build the Docker image
    #   run: docker build . --file testes.Dockerfile --tag testes:latest

    # - name: Print Docker image size
    #   run: docker images | grep testes