name: Teste CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Testes
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: debug-annotation
      run: echo "::debug::Esta é uma anotação de debug"

    - name: warning-annotation
      run: echo "::warning::Esta é uma anotação de warning"

    - name: error-annotation
      run: echo "::error::Esta é uma anotação de error"

    - name: warning-file-annotation
      run: echo "::error file=.github/workflows/dockerteste.yml,line=5,col=5::Remova este comentario"

    - name: error-file-annotation
      run: echo "::error file=.github/workflows/dockerteste.yml,line=17,col=9::Remova tambem este comentario"

    # - name: Build the Docker image
    #   run: docker build . --file testes.Dockerfile --tag testes:latest

    # - name: Print Docker image size
    #   run: docker images | grep testes